name: nfsen_g workflow
on: [push]
jobs:  
  build_and_push_to_docker_hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push backend
        uses: docker/build-push-action@v2
        with:
          no-cache: true
          context: ./nfsen-ng/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/nfsen_g:latest
      - name: Build and Push frontend
        uses: docker/build-push-action@v2
        with:
          no-cache: true
          context: ./nfdump/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/nfdump_g:latest
      - name: Check out
        uses: actions/checkout@v2