name: nfsen_g workflow
on: [push]
jobs:  
  build_and_push_to_docker_hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push nfsen
        uses: docker/build-push-action@v2
        with:
          no-cache: false
          context: ./nfsen-ng/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/nfsen_g:latest
      - shell: bash
        run: |
          /usr/bin/docker save -o nfsen_g.tgz gaps64/nfsen_g:latest
      - name: Upload nfen_g tgz 
        uses: actions/upload-artifact@v3
        with:
          name: nfsen_g
          path: nfsen_g.tgz
      - name: Build and Push nfdump
        uses: docker/build-push-action@v2
        with:
          no-cache: false
          context: ./nfdump/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/nfdump_g:latest
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v3
        with:
          name: homework
          path: math-homework.txt
      - name: Check out
        uses: actions/checkout@v2
      - shell: bash
        run: |
          /usr/bin/docker save -o nfdump_g.tgz gaps64/nfdump_g:latest
      - name: Upload nfdump_g tgz 
        uses: actions/upload-artifact@v3
        with:
          name: nfdump_g
          path: nfdump_g.tgz
